Fixing failed automated testing FAILED tests/challenges/test_dynamic.py::test_dynamic_challenge_loses_value_properly - AttributeError: 'NoneType' object has no attribute 'name' FAILED tests/challenges/test_dynamic.py::test_dynamic_challenge_linear_loses_value_properly - AttributeError: 'NoneType' object has no attribute 'name' FAILED tests/challenges/test_dynamic.py::test_dynamic_challenge_doesnt_lose_value_on_update - AttributeError: 'NoneType' object has no attribute 'name' FAILED tests/challenges/test_dynamic.py::test_dynamic_challenge_value_isnt_affected_by_hidden_users - AttributeError: 'NoneType' object has no attribute 'name' FAILED tests/utils/test_updates.py::test_update_check_ignores_downgrades - AssertionError: assert 'https://github.com/CTFd/CTFd/releases/tag/3.7.3' is None